sudo: required
services:
  - docker

before_install: 
  - docker build -t freskimaliu/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true freskimaliu/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-test-env"
  bucket_name: "elasticbeanstalk-us-east-1-250218130509"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"